export const CART_ADD_ITEM = "CART_ADD_ITEM"
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"
export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS"
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";

export const CART_LIST_MY_REQUEST = "CART_LIST_MY_REQUEST";
export const CART_LIST_MY_SUCCESS = "CART_LIST_MY_SUCCESS";
export const CART_LIST_MY_FAIL = "CART_LIST_MY_FAIL";
export const CART_LIST_MY_RESET = "CART_LIST_MY_RESET";

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";
export const ADD_TO_CART_RESET = "ADD_TO_CART_RESET";

export const CART_REMOVE_REQUEST = "CART_REMOVE_REQUEST";
export const CART_REMOVE_SUCCESS = "CART_REMOVE_SUCCESS";
export const CART_REMOVE_FAIL = "CART_REMOVE_FAIL";
export const CART_CLEAR_SUCCESS = "CART_CLEAR_SUCCESS";

export const CART_UPDATE_REQUEST = "CART_UPDATE_REQUEST";
export const CART_UPDATE_SUCCESS = "CART_UPDATE_SUCCESS";
export const CART_UPDATE_FAIL = "CART_UPDATE_FAIL";
export const CART_UPDATE_RESET = "CART_UPDATE_RESET";