export const CART_ADD_ITEM = "CART_ADD_ITEM"
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"
export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS"
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";

export const CART_LIST_MY_REQUEST = "CART_LIST_MY_REQUEST";
export const CART_LIST_MY_SUCCESS = "CART_LIST_MY_SUCCESS";
export const CART_LIST_MY_FAIL = "CART_LIST_MY_FAIL";
export const CART_LIST_MY_RESET = "CART_LIST_MY_RESET";